### ISSUE TITLE
data persistence

### ISSUE THREAD

**Issue by ttheodorou** [tshenolo/docker-sftp-server-with-sshkey#1]
I can't get the image to work with data persistence (-v). I think it might be a user permissions issue, but since I'm not very familiar with Linux, I can't propose a solution. Have you encountered this problem?

**Comment by tshenolo** [comment]
I have fixed a few bugs in the documentation. The user is sftpuser and the ssh key docker_rsa.
Assuming that you are using docker desktop try creating a volume called sftp-uploads then run the following command:

Build the image: 
docker build -t my-sftp-server .

Run the container:
docker run -d -v sftp-uploads:/home/sftpuser/sftp/upload --name my_sftp_container -p 2222:22 my-sftp-server

Let me know if you run into other problems. 
Cheers
